---
branches:
 only:
 - master
 - develop
 - /^[0-9]+\.[0-9]+\.[0-9]+[.0-9ab]*$/

clone_depth: 2

environment:
  matrix:
# Ignoring the tox safety testenv until
#  https://github.com/pyupio/safety/issues/119 is resolved.
    -  CONDA_ROOT: "C:\\Miniconda36-x64"
       TOXENV: "py36"
    -  CONDA_ROOT: "C:\\Miniconda37-x64"
       TOXENV: "py37"

matrix:
  fast_finish: true


cache:
  - '%LOCALAPPDATA%\pip\Cache'

platform: x64

build: off

install:
  - set PATH=%CONDA_ROOT%;%CONDA_ROOT%\Scripts;%CONDA_ROOT%\Library\bin;%PATH%
  - conda info
  - python --version
  - python -m pip install --upgrade --disable-pip-version-check pip setuptools wheel tox

test_script:
  - tox
